Update DatabaseConnection.java
gsu-swe-s2019-group-1/project pull request #29
Opened 2019-04-12 18:05 UTC by Cdele

2019-04-12 18:26 UTC, flaviut commented
This PR denormalizes the database. If we're not required to have a normalized database that's fine, but if we are, this won't work.

Read the requirements and see if a normalized database is required.

2019-04-12 18:27 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> -                                new BCryptPasswordEncoder().encode("admin") +
Don't get rid of this line. If you do, that breaks logging in as the admin user.

2019-04-12 18:27 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                        "  Customer_username    TEXT     UNIQUE NOT NULL,\n" +
Capitalize consistently.

2019-04-12 18:27 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                        "  banker_username      TEXT     UNIQUE NOT NULL,\n" +
Get rid of all the "banker_". Same for the other tables.

This prefix makes it harder to write queries.

2019-04-12 18:27 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                        "  customer_user_id     INTEGER  NOT NULL REFERENCES Transactions (id),\n" +
This foreign key makes no sense. Each user has exactly one transaction?

Rework this please, to have a 1-n customer-transaction relation.

2019-04-12 18:27 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                        "  balance              INTEGER  NOT NULL,\n" +
Denormalizing this doesn't serve any propose. Remove the balance and overdraft columns.

The balance is calculated on-demand with a SELECT & SUM() query.

2019-04-12 18:27 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                        "  account_type         TEXT     NOT NULL\n" +
The account type column is redundant. There can only be customers in the customer table.

2019-04-13 19:57 UTC, Cdele commented
@flaviut check this when you can pls

2019-04-13 22:17 UTC, flaviut requested changes

2019-04-13 22:17 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                                "VALUES (0, 'Admin',
Syntax error on this line

2019-04-13 22:17 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                        "  banker_user_id                INTEGER     NOT NULL REFERENCES Banker (id),\n" +
Bankers and don't have transactions in their accounts

2019-04-13 22:17 UTC, flaviut commented on backend/src/main/java/pw/wp6/avocado_toast/invoker/DatabaseConnection.java
> +                        "  date_time                     DATETIME    NOT NULL\n" +
I don't know if sqlite supports date time.. You might have to use strings

2019-04-14 00:18 UTC, flaviut approved these changes

2019-04-14 00:18 UTC, merged